#!/usr/bin/env node
// Writes fixtures/vulnerable-app/config.js and .env, which contain
// realistic provider-format secrets so vibecheck's secrets rule has
// something to detect. Those two files are .gitignore'd and never
// committed — only this generator is tracked, and every secret value here
// is assembled from split literals so no contiguous provider-shaped string
// (sk_live_..., AKIA..., ghp_..., etc.) ever appears in git history for
// GitHub's push protection (or any other scanner) to flag.
const fs = require('fs');
const path = require('path');

const OUT_DIR = path.join(__dirname, 'vulnerable-app');

const stripeLiveKey = 'sk_liv' + 'e_51H8xyzTZaB9qLmN0pQrStUvWxYzAbCdEf12345';
const awsAccessKeyId = 'AKI' + 'AABCDEFGHIJKLMNOP';
const githubToken = 'ghp' + '_1234567890abcdefghijklmnopqrstuvwxyz12';
const dbPassword = 'C9!vQ2xR7$mZp4Lk';
const jwtSecret = 'f83jd9skalw92kd8sla' + 'JKDHF92kfj';
const dbUrlPassword = 'Xk8pQ2vN9rL4mZ';

const configJs = `// GENERATED by fixtures/generate.js — do not edit directly, do not commit.
// Intentionally vulnerable fixture: hardcoded secrets for vibecheck's secrets rule to catch.
module.exports = {
  stripeSecretKey: '${stripeLiveKey}',
  awsAccessKeyId: '${awsAccessKeyId}',
  githubToken: '${githubToken}',
  dbPassword: '${dbPassword}',
};
`;

const envFile = `DATABASE_URL=postgres://admin:${dbUrlPassword}@db.example.com:5432/prod
STRIPE_SECRET_KEY=${stripeLiveKey}
JWT_SECRET=${jwtSecret}
`;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(path.join(OUT_DIR, 'config.js'), configJs);
fs.writeFileSync(path.join(OUT_DIR, '.env'), envFile);
console.log('Generated fixtures/vulnerable-app/config.js and .env');
